export const bioPillars = [
  "Keeping our soul",
  "Therefore we are soulful",
  "Winning souls for Jesus Christ",
] as const;

export const bioParagraphs: string[] = [
  "Hello, my name is Horace Daniel DeGree, a music producer in Christian Hip Hop by the name of DANIEL DeGREE. I have a group/artist collective called SOUL CREW.",
  "It started off as an alliance in CHH built off of this concept. The reason why it was and still is an alliance is because we come against the satanic systems of this world that promote evil and try to force an agenda that Elohim did not give. It also made more sense to have it be a group as well since there were two artists and one producer. Anyway it was still the intent to have a group before that. Those two artists who started it were SERVant from Florida and a young man from New York by the name of Bhreyion. Bhreyion then decided to move on and do his own thing and it just boiled down to just SERVant and I. Bhreyion then came back and forward figuring out what he wanted to do. Finally he made a decision to continue being part of the group. After, two more artists who have joined and those two are Das The Nomad and Shamar Moses.",
  "Shamar is a young man based in Atlanta, GA who used to be a rapper in the world but then turned to Yahweh. He got married to his wife who is another addition who sings and raps named PreFranz. Both of them together have a group called Green Pastures. To me they are the perfect pair as a duo in CHH who bring Soul/Neo-Soul, boom bap and R&B. I prayed to Yahweh that he would send more artists to join and for me to work with. Then that's when Shamar started following me on the gram and I checked out his Instagram. From there we started to communicate and tell how we like each other's material and would like to work. It became a thing where we built a rapper producer relationship very quickly and have many projects/eps in the works. This guy produces as well and has many projects out already with a mind to drop music nonstop like J Dilla. So with that said, be on watch for what we have coming.",
  "Das The Nomad is a young man of God from Ohio around my age range of late 20s who has released many singles and projects in CHH. I found him one day just looking for artists on social media to work with. I decided to go to Selah The Corner's page who I had already worked with on a song called \"BETTER NOW\". At this time Selah had a challenge and there were a few rappers who did it, but one of them stood out the most to me and that was Das The Nomad. I then checked out his Instagram, sent out my musical resume and then within a few minutes we were communicating. We started talking about doing music and he said he will check my stuff out. After that, he came back to me saying that my material is fire and that he would love to work with me. I already had a project in the works entitled \"2 SIDES OF THE WAR\" which already had a single out called \"Pray 4 LA\" with EJ Swavv & Klazik which will be on both my project and theirs. Aside from that Das sent me his email for beats and I started going through beats for that project. We also talked about building his own first project in SOUL CREW. Along with that he is on a few other projects that are in the works.",
  "The collective grew even more with people like Handlez McGee from Atlanta, MITOGA from Atlanta, Kingdom Key from Detroit, Roman6 from California and one who I have built a long time friendship with who is a legend in CHH by the name of Kenny Knoxville.",
];
